### ISSUE TITLE
Audio from Twitter video embedded posts

### ISSUE THREAD

**Issue by Linkerss** [stefansundin/rssbox#16]
Hi, I would like to know is it possible to mute Audio from Twitter video autoplays or at least disable Twitter video autoplays? I'm getting this issue on Chrome and IE but I think Firefox mute embedded Twitter videos,

Thank you

**Comment by stefansundin** [comment]
Hi! Sorry for the late response.

The reason for this is because I have been embedding the videos with `<iframe>` tags. I was under the impression that my RSS reader didn't allow `<video>` tags, but I did some experimenting now and it seems to work fine. So I switched it out here: https://github.com/stefansundin/rssbox/commit/dbb42dfe973e545517dc69a6eb284eecfb94ab18

I will deploy the fix in a little bit, let me know if there are any issues in your RSS reader. Depending on your reader, it may not update old feed items.

**Comment by stefansundin** [comment]
Oh, and they shouldn't be autoplaying anymore. So I didn't mute them.

**Comment by Linkerss** [comment]
Hey Stefan, Thank you so much for your reply. It's working now. Thank you so much. I had some issues to make videos full width but I guess I managed somehow to make them full width.

The thing is I get sometimes duplicated feeds from Twitter feeds. With previous RSS Bridge I didn't get any duplicated feeds so not really sure is it Importer issue or your App issue. I use FeedWordPress Plugin. But then it could be Cron job since I've set Cron job to do updates every minute.

Also is it possible to add Instagram Hashtags feature on your App? Would be awesome to use your App on Instagram feeds too. And is it possible to remove that Privacy Policy cookies from Imgur feeds? I'm trying to add Gifs feeds from Imgur but I don't really fancy that watermark on Imgur feeds.

I just want to send you huge Thanks for your awesome work. Your App helped my website so much,

Thank you

**Comment by stefansundin** [comment]
I would appreciate if you could update the feeds less frequently. My Heroku app is really pressured now that more people are using it, and 1 minute updates are way too frequent. If you can increase the interval, that would be much appreciated.

I fear that my app will start crashing soon, and when that happens I will have to start blocking some IP addresses that abuse the free app.

Another option is to host the app yourself. It is super easy, and can be done with the Heroku free tier.

There are no plans to add hashtags at the moment. Maybe in the future. If you fork the app, you could code it yourself and then host that as your own Heroku app.

What Privacy Policy cookie are you referring to? I don't know what this is. Do you mean the Referrer-Policy header?

**Comment by Linkerss** [comment]
I'm sorry to hear that. I will do my best to host the App myself even though I have no experience with that whatsoever

**Comment by Linkerss** [comment]
Hey Stefan, Can you please advise me in details how to host the App? I created Heroku account but not really sure how to connect with your App.

If not I'll go back to old RSS Bridge because I really don't want to abuse your App,

Thank you

**Comment by Linkerss** [comment]
Hey Stefan, I deployed your App on Heroku but there's no Twitter box?

**Comment by stefansundin** [comment]
Follow these instructions: https://github.com/stefansundin/rssbox/blob/master/README.md#twitter

Here's the name of the environment variable (called "Config Vars" on heroku.com): https://github.com/stefansundin/rssbox/blob/5afd46095ff78405428c5333e618e3820a81e9af/app.json#L19

**Comment by Linkerss** [comment]
Any chance you help me with this on my Heroku account?

Thank you

**Comment by stefansundin** [comment]
Sure, I can help. You need to use your own Twitter user. I could help you if you share the Heroku app and the Twitter login (or instead of the Twitter login, you can share the consumer key and consumer secret).

Email me for more details. You can find my email address if you expand the Donate box on https://rssbox.herokuapp.com/.
