### ISSUE TITLE
There was a problem talking to Instagram. Please try again in a moment

### ISSUE THREAD

**Issue by patrickdrd** [stefansundin/rssbox#21]
There was a problem talking to Instagram. Please try again in a moment.

this since 17 hours ago...

edit: sorry for many posts, github hung when I was trying to post

**Comment by stefansundin** [comment]
Looks like something went wrong with the csrftoken, but I wasn't able to debug as much as I wanted to. I simply restarted the app and it seems to have resolved the problem since it will get a new csrftoken.

This might happen again, in which case, let me know here by posting another comment.

**Comment by stefansundin** [comment]
Ok, looks like it's happening again..

I don't have time to work on a fix now, but I'll probably get something out in the weekend.

In the mean time, if you want me to fix this, show it by sending a donation. The more I get, the more I know you all want this. Use the donation box on the website: https://rssbox.herokuapp.com/. Thank you.

**Comment by stefansundin** [comment]
I have looked a bit on this now, and it has nothing to do with the csrftoken. It looks like they have lowered the number of requests you can make from an IP address. When I restart the app, it starts working again for a moment just because the server gets a new IP.

Previously I would get 429 responses, but now they are 302 with a redirect to https://www.instagram.com/accounts/login/. I will try to make requests as a signed in user and see if it makes a difference.

Here's a timeline of 200 responses from Instagram, and you can see that they dropped to practically zero.

<img width="1412" alt="Screen Shot 2019-08-25 at 10 36 03 AM" src="https://user-images.githubusercontent.com/1991151/63653686-e9657000-c724-11e9-9d36-91666723d8f9.png">

**Comment by stefansundin** [comment]
Logging in (i.e. sending a sessionid cookie) isn't making a difference. Instead of a 302 redirect, I am now served 429 as was the case before.

This ratelimiting only seem to affect listing recent posts. Even after being ratelimited here, I am still able to request posts using the post id, and use the search function. This is why it is still possible to use the website to find Instagram feeds, but then requesting the feed itself will fail.

For now, if you can, host the app yourself and subscribe to the feeds on your own instance. Keep in mind that on Heroku, you may be using the same server as other Heroku users, so neighbors that also send requests to Instagram may affect your ratelimit.

There are lots of users of RSS Box that are sending waaay to many requests than they need to. This hurts everyone. If you are one of these users, please do not update your feeds this frequently!! You are ruining the website for everyone!! Host it yourself!

I don't think there is much I can do to fix this. The solutions that I can think of will cost me money.

**Comment by Smixite** [comment]
The issue seem to also impact me despite me hosting on my own. Any tips on improving the issue.

**Comment by p1956** [comment]
i have many IG rss, please add new setting to the config, like twitter access_token

**Comment by stefansundin** [comment]
I have now updated the code to use a different Instagram endpoint, and the sessionid no longer a requirement. You can still keep using it in case they add ratelimiting to this endpoint in the future. I didn't mention it before, but the sessionid also lets you subscribe to private feeds.

https://github.com/stefansundin/rssbox/commit/2740b92e737c2c1a12f57a3cf1498d3b85be2a07

**Comment by stefansundin** [comment]
I recently added 3611a8f34846bb9c9cd84669fbe1118fb1e46824 which removes the ability to send a `sessionid` as a parameter in the request. If you have subscribed to private feeds this way and you want to keep those feeds then your only option is to self-host RSS Box and set `INSTAGRAM_SESSIONID`.

I decided to do this since it would not be possible to support it with the caching framework that I have built. See #43.
