### ISSUE TITLE
An unhandled lowlevel error occurred. The application logs may have details.

### ISSUE THREAD

**Issue by patrickdrd** [stefansundin/rssbox#25]
where can I send you the url?

**Comment by stefansundin** [comment]
Is this for Instagram?  Feel free to paste it here if you remove the sessionid.

I probably have this error in my error reporting tool, but knowing the service and the user are causing this error will help me narrow it down.

**Comment by patrickdrd** [comment]
https://rssbox.herokuapp.com/instagram/1045381964/ini.helen?sessionid=

**Comment by stefansundin** [comment]
Okay, the bug in the app is that it currently doesn't tell you if an Instagram user no longer exists. I have a fix for that coming up.

But the real problem is that https://www.instagram.com/ini.helen/ no longer works. Either this user changed their Instagram username, or the user was deleted. The number in the url (1045381964) is the user id.

In the case that the user was renamed, then this user id can be used to find the new username. I did my best, but it doesn't appear that the user was renamed. I'd encourage you to try to google and maybe if this person has a different type of account (e.g. Twitter), then maybe they created a new user and you should hopefully be able to find a link to the new account.

Actually, I just did a search, and I think I am right:
- https://twitter.com/search?q=ines%20helene%20instagram
- https://twitter.com/crocox/status/1171777300557377536

> ‘Swedish Kim Kardashian’ Ines Helene Just Deleted Her Instagram, And Everyone Is In Mourning
