### ISSUE TITLE
Talking to Instagram

### ISSUE THREAD

**Issue by jschav88** [stefansundin/rssbox#47]
Hi, 

Thank you for your app. I tried to deploy a instance on Heroku and when i put an URL or a username, i have this error : There was a problem talking to Instagram. Please try again in a moment.

What does it mean technically ? How to solved it ?

Thank you. 

Regards

**Comment by stefansundin** [comment]
Hi,

That's curious. The official RSS Box is used by a lot of people and is being rate limited due to the number of people using it. But Heroku also pools applications together so your application may be sharing an external IP address with other Heroku customers who may also be reaching out to Instagram.

You could try restarting your application (`heroku restart`) and hope that it will receive a new IP address that isn't shared with other applications that talk to Instagram. This is a bit of shot in the dark though. You can also try getting the logs with `heroku logs` and see if you can get at the specific error it logs.

Otherwise you may want to try hosting it some other way. I just made sure that the Instagram code still works, and it appears to be working on my local computer at least. When I get time to finish the caching code that should stabilize the main app.

**Comment by eyoungmin** [comment]
1. You must enter a numeric ID. [https://codeofaninja.com/tools/find-instagram-user-id/](https://codeofaninja.com/tools/find-instagram-user-id/)
2. Instagram has added conditions that require login. RSSBOX works. However, you may need to insert a session ID.

**Comment by jschav88** [comment]
Hi, 

@stefansundin : I tried, but no change. Same error. But Eyoungmin's solution works.

@eyoungmin Thank you. It works with https://{custom}.herokuapp.com/instagram/{num-uid}/{uid}... but, like you say, it will be very cumbersome to change the RSS feed URL. 

Too bad 😔
