### ISSUE TITLE
This endpoint should not be used by a robot.

### ISSUE THREAD

**Issue by amblerkr** [stefansundin/rssbox#56]
> This endpoint should not be used by a robot. RSS Box is open source so you should instead reimplement the thing you need in your own application.

I set up and used the domain in the existing Heroku. I deleted the domain setting.
I created a new RSS Box. And I set the same domain. Such a phrase is displayed and does not work. 
It works well at Heroku app url.

Help me.

**Comment by stefansundin** [comment]
Hey. Sorry, I added a new "protection" in f4310c1a459dbd680a4c831f26cf2e5bfb0e124d.

There's a lot of people who have subscribed to feeds using the lookup endpoint, i.e. https://rssbox.herokuapp.com/instagram?q=nasa instead of the fully resolved endpoint, i.e. https://rssbox.herokuapp.com/twitter/11348282/NASA. What happens in this case is that every time their RSS reader tries to update the feed, they make two requests instead of just a single one. I decided that I wanted to try to block these so that the limited resources of the publicly faced instance is preserved.

So basically the change is that now a good `Referer` header is required to use the lookup endpoints. If you have feeds that are subscribed to these endpoints then you just need to update the URLs to the fully resolved URLs, and everything should be good.

If that's not the problem then please let me know what your browser setup is and we can try to resolve the problem. If you are able to then please have a look in your browser devtools to see if the network request includes a Referer header, and what the value is of it.

If you're running your own fork then feel free to temporarily roll back to an old version, or revert that commit until we figure out what is going on.

**Comment by onli** [comment]
Hey @stefansundin. I actually use rssbox as part of a bigger project, where robot access is what is needed. For a server move I was now updating also the rssbox installation, and subsequently got bit by this.

Is there an alternative endpoint my application should access now? If not, can this protection be disabled by config?

The whole point of using rssbox for me is not having to reimplement these parts of your app :)

**Comment by stefansundin** [comment]
@onli Sorry about that. Yes, by adding `Mozilla/` in the user-agent header and adding a fake referer header you can bypass this. Example:

```
curl -i -H 'User-Agent: Mozilla/5.0 MyRobot' -H 'Referer: https://rssbox.fly.dev/' https://rssbox.fly.dev/youtube?q=jawed
```

I'd love to learn more about your use case. This protection was added because users were subscribing their RSS readers to the lookup endpoint, meaning that every time a feed was fetched, it made two requests to RSS Box instead of only one. That's why I added this.

Are you using RSS Box to look up users on these services, and then parsing the redirect destination? I think the look up logic could easily be duplicated if that's the case.

**Comment by stefansundin** [comment]
Good idea about adding config to disable this. There are many things that should be configurable but aren't, sorry about that.

**Comment by stefansundin** [comment]
Thanks for the explanation.

I will hopefully add a configuration environment variable in the next 24 hours. If you can't wait then try adding the headers as I said before.

**Comment by onli** [comment]
That'd be awesome, thank you!

**Comment by stefansundin** [comment]
@onli A new docker image has been pushed. Pull it and set `CSRF_PROTECTION=off` and you should be good.

**Comment by onli** [comment]
@stefansundin Thanks, this worked! :)
