### ISSUE TITLE
Instagram shows only first posts

### ISSUE THREAD

**Issue by vwkd** [stefansundin/rssbox#58]
It seems Instagram fetches only the first 12 posts.

For subsequent fetches it might not matter as long as the amount of new posts in between fetches is smaller than 12. But for the initial fetch it does, as old posts are missing.

For 3 columns per row this equals 4 rows, which leads me to suspect it might be the default amount of posts visible on the screen without scrolling down to load more.

A quick glance through the code at https://github.com/stefansundin/rssbox/blob/master/app/services/instagram.rb seems to confirm the logic to scroll down might be missing?

Running e6ee86f on Heroku using INSTAGRAM_SESSIONID of newly created account.

**Comment by stefansundin** [comment]
Hello.

This behavior is actually intended. To reduce the number of requests going to Instagram, only the recent posts are fetched. The app doesn't know if this is the first time _you_ are fetching the feed, since the access is anonymous.

Instagram is not really special in this regard. But the "most recent" page gets very few posts, which maybe makes it stand out more.

But even if code was written to support the concept of an "initial fetch" which downloads more data, I don't know if I would use that for Instagram because the low rate limit is making it basically impossible to provide public access. I'm not very optimistic about continuing to support Instagram because of the problem of getting it to work on the public RSS Box instance. I am actually not running my own private instance of RSS Box, but maybe I should try to do that just to see how well Instagram works when using it just for my own feeds.

Anyway, that's my current thoughts on the matter. I'm curious what other people think, so if anyone else has thoughts about this then feel free to post them here.
